channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - rise
  - pip
  - pip:
    - jupyter_contrib_nbextensions
  - jupyter:
    - contrib nbextension install --user
    - nbextension enable rubberband/main
    - nbextension enable exercise/main
